i2samp.sh
Makes use of `pt-os-dashboard` directory, rather than `pt-dashboard` from older versions.
=> Correctly identify newer versions of pi-topOS

adafruit-pitft.sh
Hello,
I just tried adafruit-pitft.sh script and it seems "warning" function is missing : 
```
[PITFT] System update
Checking for correct software repositories...
./adafruit-pitft.sh: line 160: warning: command not found**
Updating apt indexes...
.........
```
The script is continuing instead of stopping because of this (although the script terminates with no other errors and the very nice 2.8" tft seems to work anyway).
Took  me a little way to understand that this was not a warning because of an unexisting command rather than an error because "warning" was a non existing command ;-) 
I created a (very) simple warning function.
Not sure if this is the way to contribute... but here is a PR.
JS
=> added missing warning function to adafruit-pitft.sh

read-only-fs.sh
Keep cron so time tasks are still possible. If there's no internet connection, of course only interval will be correct, but not the execution time.
If there's an internet connection, ntp will set the time after boot, and then even the execution time will be right.
=> Keep cron & install ntp

rgb-matrix.sh
=> rgb-matrix.sh: use newer sha1 of github.com/hzeller/rpi-rgb-led-matrix

i2samp.sh
Installs service file in /etc/systemd/system/, then disables.  Prompts user to enable, and triggers reboot dialog if installed.
=> add optional aplay-at-startup service to i2samp.sh

adafruit-pitft.sh
Hopefully fixes glitchiness described in [this forum thread](https://forums.adafruit.com/viewtopic.php?f=47&t=142746&p=707588).
Tested on Pi 1; appears to be working.
=> pitft: add ExecStartPre sleep of 10 seconds before starting fbcp

i2samp.sh
It's better to add -f S16 option into aplay command so that improve muffled sound.
=> Add -f S16 option

i2samp.sh
The aplay service plays `/dev/zero` to avoid clicks. The current version uses a sampling rate of 48 kHz, while ALSA is configured to use 44.1 kHz  (some lines above in `i2samp.sh`).
This leads to ALSA/dmixer resampling the silence to the right rate, which is unnecessary. CPU usage is much better if the sampling rate is set correctly in aplay (tested on a Raspberry Pi 3).
=> aplay: change rate to 44100 to avoid unnecessary CPU usage

libgpiod.sh
Fixes #53. Needed for guide since DragonBoard 410c runs Python 3.7.
=> libgpiod.sh doesn't assume Python 3.5 anymore

adafruit-pitft.sh
This change attempts to install libts0 for Buster and if that fails, it tries tslib for older versions of Raspbian.
Fixes #46. Fixes #55.
=> Fixes PiTFT Installer for Buster

rgb-matrix.sh
The existing commit reference for hzeller's library points to a version of which doesn't support the recently released Raspberry Pi 4. Edited the script to point to the new commit before running it and it started working fine on the Pi4.
=> Update library reference to support Pi 4

adafruit-pitft.sh
Fixes #59. Note that screen scaling appears to be off (like either the touch input area is smaller than the display or perhaps the display just isn't showing the full desktop), but at least the mouse pointer moves in the correct direction now, which is a definite improvement.
=> Fixes Capacitive screen rotation in buster

i2s_mic_module/Makefile, i2s_mic_module/README.md, i2s_mic_module/dkms.conf, i2s_mic_module/snd-i2smic-rpi.c, i2s_mic_module/snd-i2smic-rpi.h, i2smic.sh
This is a combination of things.
The information and driver provided here:
https://forums.adafruit.com/viewtopic.php?f=50&t=158316#p800937
works. However, it is a very hands on approach, requiring manual edit, build, and install. The driver here is a little fancier:
https://github.com/opencardev/snd-i2s_rpi
and provides a command line parameter for specifying the specific Pi model. That approach was taken here. It was updated with Pi 4 info and cleaned up a bit. All the source code is added in the subdir `i2s_mic_module`.
The DKMS install approach was tested and worked. All the install steps are captured in the new install script `i2smic.sh`.
=> Add I2S mic setup

adafruit-pitft.sh
For #83 
Simply adding a second line to match latest pattern and leave existing line for back compat. Tested as far as confirming that a `touchscreen` symlink is created:
```console
pi@raspberrypi:~ $ ls /dev/input
by-path  event0  mice  mouse0  touchscreen
```
**Additional info FWIW**
Obtained with `2020-02-13 Raspbian Lite` on a Pi 3.
```console
pi@raspberrypi:~ $ dmesg | grep input
[    7.519706] input: generic ft5x06 (11) as /devices/platform/soc/3f804000.i2c/i2c-1/1-0038/input/input0
pi@raspberrypi:~ $ udevadm info --attribute-walk --path=/devices/platform/soc/3f804000.i2c/i2c-1/1-0038/input/input0
Udevadm info starts with the device specified by the devpath and then
walks up the chain of parent devices. It prints for every device
found, all possible attributes in the udev rules key …
```
=> Update udev rule for cap touch

i2smic.sh
Possible fix for #96 
The DKMS (Dynamic Kernel Module Support) approach was *suppose* to allow for automatic driver re-building against any new kernel updates that happened on the system. But...didn't really work out that way (see forum thread from issue).
This PR simply reverts to a more basic manual install approach. The driver is built and installed using the Makefile. The script would need to be run again to repeat this process after any system updates to a new kernel. Or one could just run the Makefile directly.
Some updates will be needed to the Learn Guide as well.
=> Remove I2S mic driver DKMS

adafruit-pitft.py
It was failing if rotation wasn't provided as a parameter.
=> Bug fix for running pitft script interactively

adafruit-pitft.py, overlays/minipitft13-overlay.dts
Fixes #128. It looks like something changed with driver and it was not working in rotations other than 0. I used the driver for the 1.14" and adjusted the backlight pin. Tested with MiniPiTFT 1.3", PiTFT Bonnet 1.3", and BrainCraft HAT. Tested with various rotations in console and HDMI mirroring with successful results. Also fixed an issue where setting rotation to 0 ended up with 90 degree rotation due to a typo.
=> Fix 80 row offset issue for 1.3" display

adafruit-pitft.py, overlays/minipitft13-overlay.dts
This rolls back the 1.3" driver due to issues users were having with the braincraft hat. This also has a couple small script fixes including apt upgrade was waiting for user input, but not letting the user know to press Y. Some extra "#dtoverlay=vc4-fkms-v3d" were being added to the config which was annoying.
=> Roll back driver + couple small script fixes

adafruit-pitft.py, st7789_module/st7789v_ada.c
Ok, this PR does 2 things.
First it fixes the driver so it compiles under Kernel 5.10 and 5.4.
Second, it runs the pinning script as part of the PiTFT install process if the version is greater than 5.4.
Fixes #149.
=> Add pinning to pitft and fix driver

adafruit-pitft.py, raspi-blinka.py, rpi_pin_kernel_firmware.py
* The removes automatic pinning from adafruit-pitft.py because there was a kernel release on Feb 1 that appears to at least be working with the lite version.
* Removes `sudo apt update` from raspi-blinka since it was redundant and is now displaying a warning.
* Makes the update in raspi-blinka show the output
* Made a Python version of the pinning script.
=> Script fixes and updates

raspi-blinka.py
Dependency check for RPi.GPIO which is a dependancy for: Adafruit_Blinka/src/adafruit_blinka/microcontroller/bcm283x/pin.py
RPi.GPIO is not included in all Raspberry Pi OS images and may not be installed on the host E.G. Raspberry Pi OS Lite.
=> Dependency check for RPi.GPIO

adafruit-pitft.py
Fixes #159. Also removes warnings from device tree compiler.
=> Fix script crashing on non st7789 displays

adafruit-pitft.py
libraspberrypi-dev & build-essential are needed for the compiling of FBCP. These are missing on some debian based operating systems. I'm running dietpi on a raspberrypi 3 and it failed to build.
Ubuntu mentioned, not heard back from issue owner https://github.com/adafruit/Raspberry-Pi-Installer-Scripts/issues/89
=> Fix for FBCP fail on various debian based OS

adafruit-pitft.py, raspi-spi-reassign.py
This will make it easy for users to get around the OS twiddling with CE0/CE1 for CircuitPython. If useful, we can move some of the functionality into the raspi-blinka script.
=> Added script to handle reassigning CE0/CE1 for SPI

rpi-pin-kernel-firmware.sh
This fixes 2 issues. First, the version isn't hardcoded anymore. Second, newer versions are formatted like "1:1.20210527-1" and it works with those now.
=> Fix pinning script to work on recent versions of kernel

overlays/minipitft114-overlay.dts, overlays/minipitft13-overlay.dts, overlays/st7789v_240x320-overlay.dts, overlays/tftbonnet13-overlay.dts
Hard to believe the fix was so simple, but when you run out of documented suggestions that don't seem to work and just start trying your own wacky ideas, sometimes it just works out that way.
Fixes #187. Fixes #189.
=> Change backlight on ST7789 displays to be on by default

i2samp.sh
=> Add bullseye to i2samp version check

read-only-fs.sh
This script is neutralized (exits on startup after a brief message) but I’m not comfortable deleting it yet, in case someone was still relying on it. Perhaps in a few months or a year if there’s no activity, it can be removed.
=> read-only-fs.sh: exit with message, only keeping this temporarily

read-only-fs.sh
1. tmpfs and systemctl on latest raspberry os breask ntp because /tmp is private to ntp. This results in /etc/resolv.conf symbolic link to became unavailable to ntpd. 
2. read-only fs should never be fsck'ed if 'reliability' and 'boot at all cost even fs is corrupted' is the goal. Otherwise linux will check fs every 6 month (including read only fs) and if corruption is found will wait for user to confirm to continue - you dont want this.
3. fixed vim complaining about ~/.viminfo not being writable.
=> Ntp fix etc

overlays/minipitft114-overlay.dts, overlays/minipitft13-overlay.dts, overlays/st7789v_240x320-overlay.dts, overlays/tftbonnet13-overlay.dts
Raspberry Pi updated the kernel again and now the backlight is off by default. This PR basically undos #192, which seems to fix it.
=> Updated backlight to be on for latest kernel

adafruit-pitft.py
Working with the Raspberry Pi Zero 2 W and ran into the error state where whenever I was attempting to install adafruit-pitft.py installer (`sudo python3 adafruit-pitft.py`) it would not find the libts dependency. Upon investigating, it seems like on Buster the library exists but is not indexable. 
This issue is solved by installing the libts-dev dependency.
=> fix(adafruit-pitft.py): libts dependency

adafruit-pitft.py
Fixes #228.
Apparently this was done in #129 and then reverted for some reason in #157. Tested with console and fbcp and it seems to work fine on both.
@ladyada
=> Fix rotation parameter for ST7789 displays

libgpiod.py
The old instructions mentioned adafruit-python**3**-shell as a dependency but when I tried to install the package I found out that the package didn't exist ( or deprecated I think ) and I was able to use adafruit-python-shell instead. So, I thought I might add the package to the instructions in case anyone else runs into the same issue as me.
=> docs: add an alternative package if original fails

adafruit-pitft.py, i2smic.py
Fixes #248. OS apparently handles adjusting the touch stuff automatically now, so removed our invert parameters.
Tagging @ladyada.
=> Fix Capacitive 2.8-inch PiTFT touch

i2samp.sh
Please restore i2samp.h support for Raspbian buster system. I test the i2s driver on the raspbian buster system, everything works fine.
=> Please restore i2samp.h support for Raspbian buster system.

README.md
currently:
```
sudo apt-get install python3-pip click
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package click
```
=> fix `click` install

raspi-blinka.py
The file checked the python version by comparing the major and minor versions. However, the variables compared were strings, making '11' > '8' -> False, when in fact it should have been true. I converted the versions to integers before comparing, so that versions 10 and above are accepted.
=> Fix bug in python version check in raspi-blinka.py

raspi-blinka.py
Looks like the parameter for configuring serial non-interactively has changed. This PR updates it.
=> Update raspi-config serial enable

rgb-matrix.sh
When using [`rgb-matrix.sh`](https://github.com/adafruit/Raspberry-Pi-Installer-Scripts/blob/main/rgb-matrix.sh) on newer RPi OS (which ship with Python 3.11), we run into issues like https://github.com/hzeller/rpi-rgb-led-matrix/issues/1526 when trying to use this installer since Python 3.11 doesn't expose that header anymore (see https://github.com/cython/cython/issues/4461).
This PR just bumps the `rpi-rgb-led-matrix` commit to the newest version, that also includes a fix for the above problem.
=> Bump `rpi-rgb-led-matrix` commit to `a3eea9`

raspi-spi-reassign.py
This updates the raspi-spi-reassign script to allow "disabled" to be passed in via command line in addition to new pin numbers.
cc @ladyada for review
=> Allow 'disabled' to be passed in via command line in spi-reassign script

i2samp.sh
Fixes #270.
This change updates it to attempt to use the new location of config.txt first, but allows falling back for older OS. Otherwise it seemed to work fine.
=> Update i2samp to work on bookworm

adafruit-pitft-mipi.py
Tested the script on the Pi 5 with wayland and display works, but there was no desktop. Turns out the script was disabling the KMS driver. This fixes the issue.
=> Fix mipi script from messing with kms and fkms drivers

adafruit-pitft.py, overlays/pitft22-overlay.dts
This updates the PiTFT script so that it works with bookworm, but still retains backwards compatibility for now. Since FBCP is going away, I added a new type called "mirror" which is basically the same thing, but more generalized. Wayland detection added, so it will guide the user down the correct path based on whether or not they are running Wayland.
cc: @ladyada  for review
=> Update PiTFT Script and 2.2 inch overlay for Bookworm/Pi 5

adafruit-pitft.py, overlays/pitft22-overlay.dts, overlays/pitft28-capacitive-overlay.dts, overlays/pitft28-resistive-overlay.dts, overlays/pitft35-resistive-overlay.dts
These are the overlays updated in https://github.com/raspberrypi/linux/pull/5903. Since the overlays can handle both the drm and non-drm drivers, the script has been updated to reflect those.
=> Update PiTFT overlays and add resistive PiTFTs

adafruit-pitft.py
Fixes #302. So the Pi Zero W uses bullseye still (bookworm is not even an option) and after testing with the mipi driver, I found the kms driver also needs to be enabled for it to work. I added a config option so that we can selectively not have it commented out per display.
=> Don't comment out kms driver for mipi display

adafruit-pitft.py
The PiTFT 3.5" resistive display requires a drm flag to work with Pi Zero and 3B versions of Bookworm. Tested on Pi4 and Pi5 as well.
=> drm added for PiTFT 3.5" resistive

i2s_mic_module/snd-i2smic-rpi.c
After linux 6.10-rc2, kernel remove asoc_xxx() compatible macro. So use original prototypes instead.
=> upstream: no longer use asoc_xxx() compatible macro

raspi-blinka.py
Necessary for blinkatest.py to run without errors on a Pi 5.
Adds two shell commands for pi5 only. 
```
sudo apt remove python3-rpi.gpio
pip3 install rpi-lgpio
```
Tested on a Pi4 and Pi5 running Bookworm 64-bit Lite. 
Both run clean blinkatest.py after. 
You can see the script logic at the end.
```
Detected RASPBERRY_PI_4B, no additional fixes needed.
```
```
Detected Raspberry Pi 5, applying additional fixes...
```
=> pi5 GPIO packages fix

raspi-blinka.py
Tested in a venv and this is working correctly. For some reason it still tries to install RPi.GPIO as a dependency (via pip) and then this script promptly uninstalls it now, but that seems to be some weird issue with the Blinka setup script.
cc: @ladyada  for review
=> Updated Blinka installer to at least install the correct packages

adafruit-pitft.py
raspi-config was being called with W1 as enable / disable parameter instead of 0 / 1 .
=> Fix enable and disable of Wayland.

adafruit-pitft.py
Minor argument change to rapsi-config do_wayland setting. 
This is in regards to [issue# 331](https://github.com/adafruit/Raspberry-Pi-Installer-Scripts/issues/331) which is "Programmer error, unrecognized boot option" error message from adafruit-pitft.py since a January 2025 package update. raspi-config expect different arguments for do_wayland of W1, W2 and W3. I confirmed that all three work with a Pi 4B and 3.5" TFT.
=> bookworm update effects adafruit-pitft.py

adafruit-pitft.py
fix for  /boot/firmware vs /boot logic for the config.txt location
A recent change to adafruit-pitft.py is causing this error message on Pi OS Bookworm systems Pi3B and Pi4B confirmed. Likely all models are effected when setting up a TFT display on Bookworm.
```
PITFT Updating /boot/firmware/config.txt/config.txt...
Traceback (most recent call last):
File "/home/pi/Raspberry-Pi-Installer-Scripts/adafruit-pitft.py", line 944, in <module>
main()
File "/home/pi/env/lib/python3.11/site-packages/click/core.py", line 1161, in __call__                                                                                    return self.main(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/pi/env/lib/python3.11/site-packages/click/core.py", line 1082, in main    rv = self.invoke(ctx) …
```
=> adafruit-pitft.py boot_dir

adafruit-pitft.py, install_wm8960.sh, wm8960-soundcard.service
This script comes from https://github.com/ubopod/ubo_app/blob/main/ubo_app/system/install_wm8960.sh and I wrote the service file myself as it was missing. I am putting this here so that we don't need to worry about the files moving.
I tested this on a Pi 5 both desktop and light. To get it working, basically these are the steps:
install raspberry pi os
sudo apt update
sudo apt upgrade
sudo apt install git wget
wget install_wm8960.sh
wget wm8960-soundcard.service
sudo chmod +x install_wm8960.sh
sudo bash install_wm8960.sh
sudo reboot
I'll update the guide after this is merged.
=> Add working voice bonnet installer and service

adafruit-pitft.py
I found this in guide feedback. Looking at the code, the script was expecting to get a link to the folder rather than the file, so this is now fixed.
=> Fix expected get_boot_config to return folder

raspi-blinka.py
This helps in situations where a new user has been added to the device, has the sudo permissions to run the installer, but the groups to access gpio, i2c, spi, etc. had not been added.
cc @ladyada
=> Add user to hardware groups in Blinka installer

raspi-blinka.py
Fixes #357.
cc: @ladyada @FoamyGuy
=> Fix lgpio change directory location
