adafruit/Raspberry-Pi-Installer-Scripts

- adafruit-pitft.sh
Checks if we're under systemd, and if so, ensures that fbcp isn't mentioned in /etc/rc.local, and installs a new unit file to start fbcp at boot, after network.target.
If not under systemd, retains the old rc.local behavior.
I note this is the only place that the $SYSTEMD var actually seems to get checked.  I can't, at this time, vouch for what would happen on a sysvinit box.
> add service unit for managing fbcp under systemd

- occi
This adds the `occi` config helper, now with an `--install` option to install system-wide and start on boot via systemd.
> Import occi util from Adafruit-Occidentalis repo

- libgpiod.sh
See also: https://github.com/adafruit/Adafruit_Blinka/issues/43
> add @ladyada's libgpiod install instrux to script

- libgpiod.sh
I'll suss out the correct way to do this at some point; it works for the moment.
> add some hacky file copies for libgpiod python bindings

- adafruit-pitft.sh
- overlays/minipitft114-overlay.dts
- st7789_module/Makefile
- st7789_module/st7789v_ada.c
> St7789 mini pitft support

- adafruit-pitft.sh
Fixes #80. Since we don't have a PiTFT version of the display at this time, I wired it up like we show in the guide to test it and it worked great.
> Added 2.0" TFT to PiTFT script

- adafruit-pitft.sh
I added an uninstall option to help folks who want to easily use RGB_display (or the upcoming displayio) on their Pi. It makes use of existing uninstall functions and breaks out some that were part of an install into their own functions.
> Added uninstall option to PiTFT

- adafruit-pitft.sh
- overlays/minipitft13-overlay.dts
- overlays/st7789v_240x320-overlay.dts
- st7789_module/Makefile
- st7789_module/fb_st7789v.c
- st7789_module/fbtft.h
@makermelissa this should at least fix fbcp mirroring for old displays (2.2", 2.8", 3.2" and 3.5")
> 5.4 fixfbcp

- adafruit-pitft.sh
> Fix for Pi 4 portrait rotation

- adafruit-pitft.sh
Fixes #42 without messing up anything else.
> Fix touch on capacitive 2.8 display for portrait modes

- libgpiod.sh
Fixes #109. Tested both paths on a system that experienced this issue and they behaved as expected.
> Added legacy option for systems with older linux headers

- adafruit_fanservice.py
- i2smic.py
They're much shorter now. i2cmic is dependent on https://github.com/adafruit/Adafruit_Python_Shell/pull/2
> Updated both python scripts to use new Shell library

- i2smic.py
Found this while working on pitft script
> Changed positional to keyword argument

- adafruit-pitft.py
This included the click automated installer options. It probably needs more testing before updating the guide, but I thought I'd at least get a fairly complete version up here.
> Added PyTFT script

- adafruit-pitft.py
Since it's stressed to reboot in the guide, I think this is a good change.
> Setting reboot prompt to Yes as default

- i2smic.py
> Corrected location of options

- adafruit-pitft.py
Fixes #134. This was supposed to be absent rather than False.
> Fixed issue with 2.2-inch PiTFT and touchscreen param

- adafruit-pitft.py
This makes it so the braincraft hat can use the display upside down.
> Use hdmi rotation for 270 degrees

- libgpiod.py
> Converted libgpiod script

- rpi-pin-kernel-firmware.sh
route to printf must be /usr/bin/printf instead of /bin/printf
> just a little fix

- adafruit-pitft.py
Also indicate it'll take a while. I got some feedback that users thought it was stuck.
> Make pinning script output visible

- adafruit_fanservice.py
Fixes #148. This will detect if we're on a Raspberry Pi and use the Raspberry Pi fan service in that case or work like before on other boards.
> Updated Fan Service to use Raspi fan service on Raspberry Pis

- adafruit_fanservice.py
- i2smic.py
- joy-bonnet.py
- raspi-blinka.py
- rpi_pin_kernel_firmware.py
> Updated scripts to use new shell functions

- raspi-blinka.py
> Add a check for Blinka's minimum required python version

- i2smic.py
> Update i2smic.py with support for RPi CM4

- raspi-blinka.py
I was trying to add a warning if Raspberry Pi OS 64-bit was detected, but it identifies itself as Debian, so I'm just displaying what the detect OS was.
> Display which OS was detected

- adafruit-pitft.py
Fixes #195. Took a bit of trial and error, but this appears to be the fix for the PiTFT not working on Bullseye.
> PiTFT fix for bullseye

- i2smic.py
Added the new Pi Zero 2 w model.
Tested it on the new Board and works like a charm.
> Added Pi Zero 2 w model

- raspi-blinka.py
> Updated Blinka Installer to not error when release info changed

- rgb-matrix.sh
For #204. Simply updates commit hash to latest from hzeller repo.
Things built fine (see below). Command line example ran. Python examples ran.
```
~~~~~~~~~~~~~
[lots of output snipped]
~~~~~~~~~~~~~
running install
running build
running build_py
creating build/lib.linux-armv6l-3.9
creating build/lib.linux-armv6l-3.9/rgbmatrix
copying rgbmatrix/__init__.py -> build/lib.linux-armv6l-3.9/rgbmatrix
running build_ext
building 'core' extension
arm-linux-gnueabihf-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -ffile-prefix-map=/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC …
```
> Update rgb-matrix to latest hzeller commit hash

- pi-eyes.sh
> pi-eyes.sh rewrite, allows Pi 4 use (corresponding code fixes in Pi_Eyes repo)

- rgb-matrix.sh
Latest Raspberry Pi OS does not have Python 2 installed by default. Script would fail as it’s trying to install things for both 2 & 3. Now checks which are present, acts accordingly.
> rgb-matrix.sh: add checks for Python 2 & 3, only install what’s right

- i2smic.py
> Added Raspberry Pi 400 support to i2smic

- adafruit-pitft.py
Fixes #166. I tested that it still works with defaults.
> Added ability to specify boot directory as parameter

- rgb-matrix.sh
Just bothered me as I use it quite a lot! I don't know how to make a hyperlink in shell, but it would be easiest to have the link siting right there. If not feel free to reject those changes and merge the other corrections.
> Update rgb-matrix.sh With Spelling and some other useful things

- i2samp.sh
> Updated i2samp to run on 64-bit Raspberry Pi OS

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
- adafruit-pitft-mipi.py
- adafruit-pitft.py
- adafruit_fanservice.py
- joy-bonnet.py
- libgpiod.py
- pi-touch-cam.py
- raspi-blinka.py
- raspi-spi-reassign.py
- retrogame.py
- rpi_pin_kernel_firmware.py
- rtc.py
Add Bug report template to reduce asking for additional details. Apparently I hadn't pushed some of my conversions yet, so that's included.
> Add Bug report template and additional conversions

- libgpiod.py
While working on another issue, I needed to run this script and realized it was pretty outdated. Tested on a Raspberry Pi 4.
@ladyada
> Fix outdated libgpiod script

- raspi-blinka.py
> Update python version checking for versions > 3.9

- adafruit-pitft-mipi.py
- adafruit-pitft.py
- adafruit_fanservice.py
- joy-bonnet.py
- raspi-blinka.py
Fixes #259. I also updated any scripts that were using variables in the run_command positionally that I would like to change to being keyword only.
**https://github.com/adafruit/Adafruit_Python_Shell/pull/22 should be merged and released prior to this being merged.**
@ladyada
> Fix issue where blinka installs as root

- adafruit-pitft.py
- raspi-blinka.py
Fixes #264. Tested on Raspberry Pi 5.
cc @ladyada
> Update pitft to run in venv

- adafruit-pitft-mipi.py
- adafruit-pitft.py
Also, some much needed updates on the mipi version.
cc @ladyada
> New /boot/config.txt fix

- raspi-spi-reassign.py
This also adds the option to disable one or both cs pins while having SPI enabled.
> Update SPI reassignment script for Bookworm

- i2smic.py
Fixes #275.
cc @ladyada for review
> Add Pi B Rev 2 to i2smic board list

- voice_bonnet.sh
The voice bonnet driver install script doesn't correctly install on the Pi 5. I added a voice bonnet script that checks for certain issues and fixes them.
> Add voice bonnet/braincraft hat script to ensure DTOs are enabled

- adafruit-pitft.py
- overlays/pitft28-capacitive-overlay.dts
This adds the Capacitive 2.8" Display.
> Update 2.8-inch Capacitive PiTFT

- adafruit-pitft-mipi.py
- adafruit-pitft.py
This gets the remainder of the ST7789 displays working on Bookworm.
> Integrate ST7789 MIPI Script into main PiTFT Script

- raspi-blinka.py
Fixes #296. Tested on Raspberry Pi 4 with Bullseye.
CC: @ladyada for review
> Add blinka installer backwards compatibility with bullseye

- adafruit-pitft.py
> Fix bullseye compatibility with pitft script

- ar1100.py
Based on https://gist.github.com/ladyada/612b48a7263f3d93238d/, but updated to run on latest pi.
cc @ladyada: for review
> Add Kippah ar1100.py script updated for latest pi

- adafruit-pitft.py
This fixes the touch response in the latest kernel version for the touch PiTFTs. This also updates the script to use the system installed overlays, which I updated a while back and are now live.
> Update script to use X11 for PiTFT Touch displays

- i2samp.py
This updates the script to use googlevoicehat-soundcard as the device tree overlay, which adds volume control.
cc @ladyada
> Update i2samp.py to provide i2s volume control
